version: 0.0
os: linux
files:
  - source: /
    destination: /usr/bin/pythonscript/my_script.py
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 300
      runas: ec2-user
